apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storybook-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: 'playground3'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: storybook-service
                port:
                  number: 80
